defaults:
  - default
  - _self_

id: PushCube-v1
num_envs: 8
action_repeat: 1
frame_stack: 1
capture_video: False
sync_env: True

wrapper:
  _target_: sheeprl.envs.maniskill.ManiSkillWrapper
  env_id: ${env.id}
  obs_mode: state
  control_mode: pd_joint_delta_pos
  render_mode: rgb_array
