defaults:
  - default
  - _self_

id: PushCube-v1
num_envs: 8
action_repeat: 1
frame_stack: 1
max_episode_steps: 200
capture_video: True
sync_env: True

wrapper:
  _target_: sheeprl.envs.maniskill.ManiSkillWrapper
  env_id: ${env.id}
  obs_mode: rgb
  control_mode: pd_ee_delta_pos
  render_mode: rgb_array
  reward_mode: dense
