# @package _global_

defaults:
  - override /algo: ppo
  - override /env: maniskill
  - _self_

# Environment
env:
  capture_video: True
  sync_env: True

# Algorithm
algo:
  name: ppo
  vf_coef: 0.5
  clip_vloss: False
  max_grad_norm: 0.5
  rollout_steps: 128
  normalize_advantages: True
  optimizer:
    lr: 3e-4
    eps: 1e-5
  per_rank_batch_size: 64
  # # If you want to run this benchmark with older versions,
  # you need to comment the test function in the `./sheeprl/algos/ppo/ppo.py` file.
  run_test: False
  # If you want to run this benchmark with older versions,
  # you need to move the `total_steps` and the `mlp_keys` config from `algo` to the root.
  total_steps: 65536
  mlp_keys:
    encoder: [state]
  encoder:                                                                                                                                                                                                                                                                       
    cnn_features_dim: null                                                                                                                                                                                                                                                         
    mlp_features_dim: 64                                                                                                                                                                                                                                                       
    dense_units: 64                                                                                                                                                                                                                                                              
    mlp_layers: 2                                                                                                                                                                                                                                                                
    dense_act: torch.nn.Tanh                                                                                                                                                                                                                                                     
    layer_norm: false                                                                                                                                                                                                                                                            
    ortho_init: false                                                                                                                                                                                                                                                            
  actor:                                                                                                                                                                                                                                                                         
    dense_units: 64                                                                                                                                                                                                                                                              
    mlp_layers: 0                                                                                                                                                                                                                                                                
    dense_act: torch.nn.Tanh                                                                                                                                                                                                                                                     
    layer_norm: false                                                                                                                                                                                                                                                            
    ortho_init: false                                                                                                                                                                                                                                                            
  critic:                                                                                                                                                                                                                                                                        
    dense_units: 64                                                                                                                                                                                                                                                              
    mlp_layers: 0                                                                                                                                                                                                                                                                
    dense_act: torch.nn.Tanh                                                                                                                                                                                                                                                     
    layer_norm: false                                                                                                                                                                                                                                                            
    ortho_init: false  

# Buffer
buffer:
  share_data: False
  size: ${algo.rollout_steps}
  memmap: False

fabric:
  devices: 1
  accelerator: cuda

checkpoint:
  every: 70000
  save_last: False

metric:
  log_every: 70000
  log_level: 0
  disable_timer: True