# @package _global_

defaults:
  - override /algo: sac
  - override /env: maniskill
  - override /model_manager: sac
  - _self_

# Algorithm
algo:
  total_steps: 250000
  per_rank_batch_size: 1024
  mlp_keys:
    encoder: [state]
    decoder: [state]
  cnn_keys:
    encoder: []
    decoder: []

  # Entropy coefficient
  alpha:
    alpha: 0.2
    optimizer:
      lr: 3e-4
      eps: 1e-4
  gamma: 0.8

# Checkpoint
checkpoint:
  every: 5000

# Buffer
buffer:
  size: 1000000
  checkpoint: True
  sample_next_obs: False


metric:
  aggregator:
    metrics:
      Loss/value_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Loss/policy_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Loss/alpha_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
